

services:
  app:
    container_name: app
    image: registry.sedrehgroup.ir/eye_of_develop_app:latest
    ports:
      - "8000:8000"
    restart: 'always'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - main
    volumes:
      - ./backend:/app  


  db:
    container_name: database
    image: registry.sedrehgroup.ir/postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - main

networks:
  main:


